CMS/urls.py
from django.urls import include, path
from .views import leadViews,contactViews, meetingView

#below is the namespace of urls of mystatic app

app_name = 'cms'
urlpatterns = [

    # /index/
    # path('', album_view.IndexView.as_view(), name='index'),

    # /mystatic/<album_id>
    # path('<pk>', album_view.DetailView.as_view(), name='details'),
    path('lead/',leadViews.IndexView.as_view(),name='index'),
    path('lead/details/<pk>/', leadViews.LeadView.as_view(), name='lead-details'),
    path('lead/add/', leadViews.LeadCreate.as_view(), name='lead-add'),
    path('contact/add/<lead_id>',contactViews.ContactCreate.as_view(), name='contact_add'),
    path('meeting/add/<lead_id>',meetingView.MeetingCreate.as_view(), name='meeting_add'),
    path("meeting/view",meetingView.ViewMetting.as_view(),name="view_meeting"),
    path("meeting/update/<pk>/<lead_id>", meetingView.MeetingUpdate.as_view(), name="update_meeting"),
    path("api/meeting/update/<pk>",meetingView.api_json_field_update, name="update_jsonfield")

]

CMSPROJECT/urls.py
from .router import router
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('',home_view,name='home'),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('accounts/', include('accounts.urls')),
    path('cms/',include('CMS.urls')),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),name="password_reset_done"),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),

]

# print(router.urls)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CMS/models.py
from django.db import models
from datetime import date
from enum import Enum
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django_mysql.models import JSONField

# Create your models here.
private_storage = FileSystemStorage(location=settings.MEDIA_URL)
class Stage(Enum):
    LEAD = 1
    POTENTIAL = 2
    OPPORTUNITY = 3
    CUSTOMER = 4

class Lead(models.Model):
    stage = models.CharField(max_length=250,default=Stage.LEAD.name)
    name = models.CharField(max_length=250,unique=True)
    address = models.CharField(max_length=250, default=None,blank=True,null=True)
    email = models.EmailField(max_length=250, default=None)


    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=250)
    primary = models.BooleanField(default=False)
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=250,default=None)

    def __str__(self):
        return self.name


class Meeting(models.Model):
    title = models.CharField(max_length=250)
    avenue = models.CharField(max_length=250)
    stage = models.CharField(max_length=12)
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    about = models.TextField(default=None)
    conclusion = models.TextField(default=None)
    minute = models.FileField(default=None,storage=private_storage)
    jsonTest = JSONField()

    def __str__(self):
        return self.title


class Contract(models.Model):
    title = models.CharField(max_length=250)
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    description = models.TextField(default=None)
    attachment = models.FileField(default=None)

    def __str__(self):
        return self.title


class Product(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField(default=None)

    def __str__(self):
        return self.name


class ContractProduct(models.Model):
    contract = models.ForeignKey(Contract, on_delete=models.PROTECT, related_name='contract')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='product')

CMS/views.py
from django.shortcuts import render
import os
from django.conf import settings
from django.http import HttpResponse, Http404
# Create your views here.
def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

CMS/views/contactViews.py
from CMS.form import ContactForm
from django.shortcuts import redirect, render
from django.views.generic import View
from CMS.models import Lead, Contact
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class ContactCreate(View):
    form_class = ContactForm
    template_name = 'cms/new_contact.html'

    def get(self,request,lead_id):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form,'lead_id':lead_id})

    def post(self, request,lead_id):
        form = self.form_class(request.POST)
        try:

            post_data = request.POST.dict()
            lead = Lead.objects.get(id=lead_id)

            if form.is_valid():
                if post_data.get('primary'):

                    if Contact.objects.all().filter(primary=True).filter(lead__id=lead_id).exists():
                        messages.error(request, 'Customer Can only have one primary contact')
                        return render(request, self.template_name, {'form': form, 'lead_id': lead_id})
                    else:
                        contact = form.save(commit=False)
                        contact.__setattr__('lead', lead)
                        contact.save()
                else:
                    contact = form.save(commit=False)
                    contact.__setattr__('lead', lead)
                    contact.save()
            return redirect('cms:lead-details', lead.id)
        except Exception as e:
            messages.error(request, 'Error Occurred try Again')
            return render(request, self.template_name, {'form': form, 'lead_id': lead_id})

CMS/views/leadViews.py
import time

from django.views import generic
from CMS.form import LeadForm
from django.shortcuts import render,redirect
from django.views.generic import View
from CMS.models import Lead, Stage
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'cms/leads.html'
    context_object_name = 'leads'

    def get_queryset(self):
        return Lead.objects.all()


@method_decorator(login_required, name='dispatch')
class LeadView(generic.DetailView):
    stage = ''

    def get(self,request, pk='lead_id',**kwargs):
        lead = Lead.objects.get(pk=pk)
        if Stage[lead.stage].value != 4:
            self.stage = Stage(Stage[lead.stage].value+1).name
        return render(request, 'cms/lead_details.html', {'lead': lead, 'stage': self.stage})


@method_decorator(login_required, name='dispatch')
class LeadCreate(View):
    form_class = LeadForm
    template_name = 'cms/registration/newLead_form.html'
    details_template = 'cms/lead_details'

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        try:


            if form.is_valid():
                lead = form.save(commit=False)
                lead.save()
                return redirect('cms:lead-details', lead.id)
            else:
                return render(request, self.template_name, {'form': form,})
        except Exception as e:
            messages.error(request, e)
            return render(request, self.template_name, {'form': form})



def job():
    print("hello")

CMS/views/meetingView.py
from django_mysql.models.functions import RegexpReplace, JSONExtract

from CMS.form import MeetingForm
from django.shortcuts import redirect, render
from django.views.generic import View
from CMS.models import Lead,Meeting
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status


@method_decorator(login_required, name='dispatch')
class MeetingCreate(View):
    form_class = MeetingForm
    template_name = 'cms/new_meeting.html'

    def get(self,request,lead_id):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form,'lead_id':lead_id})

    def post(self, request,lead_id):
        form = self.form_class(request.POST, request.FILES)
        try:

            lead = Lead.objects.get(id=lead_id)
            if form.is_valid():
                meeting = form.save(commit=False)
                meeting.__setattr__('lead', lead)
                # meeting.attrs = {"people":[{"name":"ndayambaje","age":1},{"name":"john","age":1}]}
                meeting.save()
                return redirect('cms:lead-details', lead.id)
            return render(request, self.template_name, {'form': self.form_class, 'lead_id': lead_id})
        except:
            messages.error(request, 'Error occurred while saving new Meeting, try again later')
            return render(request,self.template_name,{'form':self.form_class,'lead_id':lead_id})

class MeetingUpdate(View):
    form_class = MeetingForm
    template_name = 'cms/new_meeting.html'

    def get(self, request, pk="pk", lead_id="lead_id"):
        meeting = Meeting.objects.get(pk=pk)
        form = self.form_class(instance=meeting)
        return render(request,self.template_name,{'form':form,'lead_id':lead_id})

    def post(self, request, pk="pk",lead_id="lead_id"):
        meeting = Meeting.objects.get(pk=pk)
        form = self.form_class(request.POST, request.FILES,instance=meeting)

        if form.is_valid():
            meeting = form.save(commit=False)
            meeting.jsonTest['name'] = "SAKIPU"
            meeting.save()
            print("test")
        return render(request, self.template_name, {'form': form, 'lead_id':lead_id})


@api_view(['POST', ])
def api_json_field_update(request, pk="pk"):
    meeting = Meeting.objects.get(pk=pk)
    meeting.jsonTest["people"] = request.data["people"]
    meeting.save()
    print(filter(lambda person: person['name'] == 'Malia', meeting.jsonTest["people"]))
    return Response(meeting.jsonTest, status.HTTP_200_OK)




class ViewMetting(View):

    def get(self,request):
        try:
            # meetings = Meeting.objects.filter(jsonTest__people__contains={"name":"Suleiman"})
            # meetings = Meeting.objects.filter(jsonTest__name="BAGABO")
            # meetings = Meeting.objects.filter(jsonTest__has_key="test")
            meetings = Meeting.objects.filter(jsonTest__has_any_keys=["people","test"])

            print(meetings)
            return render(request,"cms/registration/mettings.html",{'meetings':meetings})
        except:
            return render(request,"cms/registration/mettings.html")

CMS/templates/cms/homepage.html
{% extends 'base.html' %}
  {% block title %}Lead Details{% endblock %}
{% block body %}

    <div class="row mt-5">
        <div class="col-md-12 offset-4 mt-5">
            <h1 class="mt-5">Welcome to CMS</h1>
        </div>
    </div>

{% endblock %}

CMS/templates/cms/lead_details.html
{% extends 'base.html' %}
  {% block title %}Lead Details{% endblock %}
{% block body %}
    <div class="row">
      <input type="hidden" value="{{ lead.id }}" id="lead_id">
       <div class="col-md-4">
           <div class="card">
              <div class="row ml-1">
                  <div class="col-md-12 mb-2">Name: {{ lead.name }}</div>
                  <div class="col-md-12 mb-2">Email: {{ lead.email }}</div>
                  <div class="col-md-12 mb-2">Address: {{ lead.address }}</div>
                  <div class="col-md-12 mb-2 default">
                  </div>

                  <div class="col-md-12 mb-2" id="stageview">
                      <a class="btn btn-sm btn-primary" id="triger_stage" href="javascript:void(0)">Next stage</a>
                  </div>
                  <div class="col-md-12  mb-2 invisible ajaxresult"></div>
              </div>
           </div>
       </div>
    </div>

    <div class="row mt-4">
       <div class="col-md-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Contacts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Meeting</a>
              </li>

            </ul>
            <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                  <div class="row mt-3">
                      <div class="col-md-4 offset-1">
                         <div class="row ml-3">
                             <a class="btn btn-primary" href="{% url 'cms:contact_add' lead.id %}">New </a>
                         </div>
                     </div>
                  </div>
                  <div class="row mt-5">
                      <div class="col-md-8 offset-1">
                         <table class="table table-hover" id="contacts" >
                             <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Phone</th>
                                    <th>Email</th>
                                    <th>Is Primary</th>
                                    <th>Action</th>
                                </tr>
                             </thead>
                             <tbody>
{#                             {% for contact in lead.contact_set.all %}#}
{#                                 <tr>#}
{#                                    <td>#}
{#                                        {{ contact.name }}#}
{#                                    </td>#}
{#                                    <td>#}
{#                                         {{ contact.phone }}#}
{#                                    </td>#}
{#                                   <td>#}
{#                                        {{ contact.email }}#}
{#                                   </td>#}
{#                                   <td>#}
{#                                        {% if contact.primary %}#}
{#                                            YES#}
{#                                        {% else %}#}
{#                                            NO#}
{#                                         {% endif %}#}
{#                                   </td>#}
{##}
{#                                 </tr>#}
{#                             {% endfor  %}#}
                             </tbody>
                         </table>
                      </div>
                  </div>
              </div>
              <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                   <div class="row mt-3">
                      <div class="col-md-4 offset-1">
                         <div class="row ml-3">
                             <a class="btn btn-primary" href="{% url 'cms:meeting_add' lead.id %}">New </a>
                         </div>
                     </div>
                  </div>
                  <div class="row mt-5">
                      <div class="col-md-10 offset-1">
                          <table class="table table-hover">
                              <thead>
                                <tr>
                                    <th width="20%">Title</th>
                                    <th>Avenue</th>
                                    <th>Date </th>
                                    <th>Meeting Minute</th>
                                    <th width="30%">About</th>
                                    <th width="30%">Conclusion</th>
                                </tr>
                              </thead>
                              <tbody>
                                 {% for m in lead.meeting_set.all %}
                                     <tr>
                                         <td>{{ m.title }}</td>
                                         <td>{{ m.avenue }}</td>
                                         <td width="10%">{{ m.date|date:'d-m-y' }}</td>
                                         <td>
                                             <a class="btn btn-sm btn-primary" href="{{ m.minute.url }}" target="_blank" type="application/octet-stream" download>
                                                 <i class="fa fa-download"></i>
                                                 Download
                                             </a>
                                         </td>
                                         <td>{{ m.about }}</td>
                                         <td>{{ m.conclusion }}</td>
                                     </tr>
                                 {% endfor %}
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>

            </div>
       </div>
    </div>

{#    Modal#}
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div id="stagemsg"></div>

      </div>
        <input type="hidden" value="{{ lead.id }}  " id="leadid" >
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="change_stage">Change Stage</button>
      </div>
    </div>
  </div>
</div>





    <div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="message">

      </div>
        <input type="hidden"  id="contactId" >
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="changeContactStatus">Confirm</button>
      </div>
    </div>
  </div>
</div>



    <script>
        var stage=''
       $(function(){
            f()
            viewContacts()
       })

     $(document).on('click', '#triger_stage', function (e) {
         $("#stagemsg").text(' You about to move this Lead to '+stage+' stage are you sure')
         $("#exampleModal").modal()
     });
      $(document).on('click','#change_stage',function () {
          {#console.log($('#leadid').val())#}
          $.ajax({
					url:"http://localhost:8000/api/leads/"+$('#leadid').val()+"/change_stage/",
			        type : "GET",
			        contentType: 'application/json',
			        success : function(result, textStatus, jQxhr) {
                        //$("#ra_save").removeClass('disabled');
                        console.log(result);
                        if(result.code === 200){
                            $("#exampleModal").modal('hide');

                            $('.ajaxresult').addClass('text-info').text("Stage Changed successfully").removeClass('invisible')
                             f();
                        }else{
                             $('.ajaxresult').addClass('text-danger').text('Stage not changed').removeClass('invisible')
                        }
					}

					});
      })

      function f() {
           $.ajax({
                    url:"http://localhost:8000/api/leads/"+$("#lead_id").val()+"/stage",
			        type : "GET",
			        contentType: 'application/json',
			        success : function(result, textStatus, jQxhr) {
                        //$("#ra_save").removeClass('disabled');
                        console.log(result)
                        $('.default').text('Stage: '+result.lead.stage);
                        stage=result.stage
                        if(result.lead.stage==='CUSTOMER'){
                            $("#stageview").addClass('invisible')
                        }else{
                            $("#stageview").removeClass('invisible')
                        }
					}
					});
      }



    function viewContacts() {
           $.ajax({
                    url:"http://localhost:8000/api/contacts/"+$("#lead_id").val()+"/bylead",
			        type : "GET",
			        contentType: 'application/json',
			        success : function(result, textStatus, jQxhr) {
                        if(result.contacts.length!=0){
                             $("#contacts .ctr").remove();
                        }

                        if(result.code===200){
                             var trHTML =''

                             $.each(result.contacts, function(i, item) {
                                   let primary=(item.primary)? "YES":"NO"
                                   let primaryAction=''
                                   let contacId='<input type="hidden" id="contactIdValue" value="'+item.id+'">'

                                     if(item.primary){
                                         primaryAction='<a href="javascript:void(0)" class="btn btn-sm btn-danger" id="turnToRegular">Make Regular Contact</a>'
                                     }else{
                                         primaryAction='<a href="javascript:void(0)" class="btn btn-sm btn-primary" id="turnToPrimary">Make primary Contact</a>'
                                     }

                                   trHTML += "<tr class='ctr'>"
                                         +'<td>'+item.name+'</td>'
                                         +'<td>'+item.phone+'</td>'
                                         +'<td>'+item.email+'</td>'
                                         +'<td>'+
                                            primary
                                         +'</td>'
                                           +'<td>'+
                                             primaryAction+''+
                                             contacId
                                           +'</td>'

                                   +"</tr>"
                             })
                             $('#contacts tbody').append(trHTML)
                        }else{
                            console.log('not found')
                        }
					}
					});
      }

var primary=false
      $(document).on('click', '#turnToRegular', function (e) {
          primary=false
          $('#contactId').val($(this).closest('tr').find('#contactIdValue').val())
          $("#message").text('You are about to make this contact a regular contact')
          $("#contactModal").modal()
     });
      $(document).on('click', '#turnToPrimary', function (e) {
          primary=true
          $('#contactId').val($(this).closest('tr').find('#contactIdValue').val())
          $("#message").text('You are about to make this contact a Primary contact')
          $("#contactModal").modal()
     });



    {# confirm primary contact#}
    $(document).on('click','#changeContactStatus',function (){

       if(!primary){
            makeRegular()
       }else{
            makePrimary()
       }
    })



    function makeRegular(){

         $.ajax({
					url:"http://localhost:8000/api/contacts/"+$('#contactId').val()+"/regular/",
			        type : "GET",
			        contentType: 'application/json',
			        success : function(result, textStatus, jQxhr) {

                        if(result.code === 200){
                            viewContacts()
                        }else{

                        }
					}

					});
     $("#contactModal").modal('hide')
    }





    function makePrimary(){
         $.ajax({
					url:"http://localhost:8000/api/contacts/"+$('#contactId').val()+"/primary/",
			        type : "GET",
			        contentType: 'application/json',
			        success : function(result, textStatus, jQxhr) {

                        if(result.code === 200){
                            viewContacts()
                        }else{
                           alert(result.msg)
                        }
					}

					});
           $("#contactModal").modal('hide')
    }

    </script>
{% endblock %}

CMS/templates/cms/new_contact.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title %}Add new Contact{% endblock %}
 {% block body %}

     <div class="row">
       <div class="col-md-4 offset-4">
           <div class="card">
               <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                              <h5>New Contact</h5>
                        </div>
                        <div class="col-md-6">
                            <a href="{% url 'cms:lead-details' lead_id %}" class="pull-right">
                                   <i class="fa fa-times"></i>
                             </a>
                        </div>
                    </div>


               </div>
               <div class="card-body">
                   {% crispy form form.helper %}

                   {% if messages %}
                        <div class="mt-3 row">
                            {% for message in messages %}
                            <div  {% if message.tags %} class="alert alert-danger col-md-10 offset-1" {% endif %}> {{ message }} </div>
                            {% endfor %}
                        </div>
                    {% endif %}
               </div>
           </div>
       </div>

    </div>

{% endblock %}

CMS/templates/cms/new_meeting.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title %}Add new Meeting{% endblock %}
 {% block body %}

     <div class="row">
       <div class="col-md-4 offset-4">
           <div class="card">
               <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                              <h5>New Meeting</h5>
                        </div>
                        <div class="col-md-6">
                            <a href="{% url 'cms:lead-details' lead_id %}" class="pull-right">
                                   <i class="fa fa-times"></i>
                             </a>
                        </div>
                    </div>

               </div>
               <div class="card-body">
                   {% crispy form form.helper %}

                   {% if messages %}
                        <div class="mt-3 row">
                            {% for message in messages %}
                            <div  {% if message.tags %} class="alert alert-danger col-md-10 offset-1" {% endif %}> {{ message }} </div>
                            {% endfor %}
                        </div>
                    {% endif %}
               </div>
           </div>
       </div>

    </div>

{% endblock %}